// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVW9ljoD3Y3R6XIkl2_y861TKqMosl5lQ',
    appId: '1:995644602070:web:59aa921c6a98a7fbb8fb77',
    messagingSenderId: '995644602070',
    projectId: 'nutripulse-f6650',
    authDomain: 'nutripulse-f6650.firebaseapp.com',
    storageBucket: 'nutripulse-f6650.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBInwxJYry6s8c00nSEpQMNdGMnKWMWrrE',
    appId: '1:995644602070:android:fce938980f7ad81eb8fb77',
    messagingSenderId: '995644602070',
    projectId: 'nutripulse-f6650',
    storageBucket: 'nutripulse-f6650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvRx9UqPYvTPa87B6QYkF0oU1q-pyoj_E',
    appId: '1:995644602070:ios:e3a7db7c3c31ea99b8fb77',
    messagingSenderId: '995644602070',
    projectId: 'nutripulse-f6650',
    storageBucket: 'nutripulse-f6650.firebasestorage.app',
    iosBundleId: 'com.example.nutripulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvRx9UqPYvTPa87B6QYkF0oU1q-pyoj_E',
    appId: '1:995644602070:ios:e3a7db7c3c31ea99b8fb77',
    messagingSenderId: '995644602070',
    projectId: 'nutripulse-f6650',
    storageBucket: 'nutripulse-f6650.firebasestorage.app',
    iosBundleId: 'com.example.nutripulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVW9ljoD3Y3R6XIkl2_y861TKqMosl5lQ',
    appId: '1:995644602070:web:70069e1abb98e5dfb8fb77',
    messagingSenderId: '995644602070',
    projectId: 'nutripulse-f6650',
    authDomain: 'nutripulse-f6650.firebaseapp.com',
    storageBucket: 'nutripulse-f6650.firebasestorage.app',
  );
}
